- src/ui/qml/NetworkSetupWizard.qml
- src/ui/qml/StartupStatusPage.qml
If tor failed before the first page was visible on screen, it would
appear to be stuck on the first setup screen, rather than displaying the
error (often that the executable is missing).
Also disabled the window height animation on Windows, as it causes some
graphical glitches.
> Fix network setup getting stuck when tor fails

- ricochet.pro
- src/core/ContactUser.cpp
- src/core/ContactUser.h
- src/core/ContactsManager.cpp
- src/core/ContactsManager.h
- src/core/UserIdentity.cpp
- src/core/UserIdentity.h
- src/protocol/ContactRequestClient.cpp
- src/protocol/ContactRequestServer.cpp
- src/protocol/IncomingSocket.cpp
- src/ui/qml/MainWindow.qml
- src/ui/qml/main.qml
First section of my [protocol branch](https://github.com/special/ricochet/compare/protocol). This implements the new protocol in ContactUser for inbound and outbound connections.
The next PR will implement chat, then contact requests, then some overall fixups and changes. All of this code is still enabled only when built with `DEFINES+=PROTOCOL_NEW`.
> Connection and user handling for new protocol

- src/core/UserIdentity.cpp
- src/core/UserIdentity.h
- src/tor/HiddenService.cpp
- src/tor/HiddenService.h
- src/ui/qml/TorPreferences.qml
It's not necessary to self-test connectivity of the hidden service
immediately after we publish it. This information isn't used for
anything valuable, and in every observed situation, we already have a
good idea of whether our service is connectable or not based on tor's
circuit status.
It has also raised some concerns, because a new Ricochet client with no
contacts will start trying to connect to some scrubbed service in the
logs.
Fixes #26
> Remove the hidden service self-testing step

- doc/protocol.md
- src/core/ContactUser.cpp
- src/protocol/Connection.cpp
- src/protocol/Connection.h
- src/protocol/Connection_p.h
- src/protocol/OutboundConnector.cpp
- src/protocol/OutboundConnector.h
Ricochet 1.0.x clients have no way of showing an error when they try to connect to clients running the newer protocol. We decided backwards compatibility would be too much extra work in this particular case, and it's still early enough to make a hard break without inconveniencing people too much.
This is an attempt to make that hard break less hard. When an _outbound_ connection is made to a known contact, and they negotiate the old protocol, it will send a chat message directing them to figure out how to upgrade:
That message is sent only once per contact, and only for outbound connections.
I don't like this solution, but since we currently lack a reliable way to tell users to upgrade, this seems like a step worth taking. Thoughts?
> Alert contacts using old protocol of the need to upgrade

- src/core/ContactUser.cpp
- src/core/ContactUser.h
- src/ui/qml/ContactList.qml
This puts contacts that are known to be running the 1.0.x versions in an "Outdated" section, until they upgrade.
One concern is that this string isn't translated, and I doubt we could get many translations for it in time.
> Show old protocol version contacts as 'Outdated'

- src/ui/qml/GeneralPreferences.qml
This mirrors the rest of the settings code, and fixes the following warning:
qrc:/ui/GeneralPreferences.qml:21:18: Unable to assign [undefined] to bool
> ui: Give a value to "always open in browser" always, if it isn't set.

- src/core/ConversationModel.cpp
- src/core/ConversationModel.h
- src/ui/qml/MessageDelegate.qml
When talking with one person throughout multiple conversations over a long
period of time, it can become hard to get a sense of how much time has passed
since a message was received. To help with this, show a separator if a long time
has passed since the last message. For now, a democratically selected hour long
duration has been chosen.
Changes from Jan's original patch:
* Use blocks rather than writing large conditionals inline
* Use Qt's default date format (justification: if the date formatting looks
"wrong" to someone, it is better that this problem be fixed within Qt, so that
more places/software benefits)
* Use seconds instead of msec for timespan durations
Done-by: Jan Noertemann <jan.noertemann@uni-dortmund.de>
> ui: Show a conversation separator if a sufficiently long timespan passes between messages.

- src/ui/qml/ChatPage.qml
This linebreak should be inserted at the cursor position, not always at
the end of the string. Also, allow alt+enter in addition to shift+enter
as a way to insert a linebreak.
Suggested by @RedLetterSec
> ui: Insert linebreak at cursor position on alt+enter

- src/ui/qml/MessageDelegate.qml
Add distinct "Copy Message" and "Copy Selection" options in place of the ambiguous "Copy" option
"Copy Message" is available when no text has been selected, or when only a link is selected, such as when a link is left-clicked. Otherwise, "Copy Selection" is available.
Resolves issue #179.
> Separate Copy options to clarify message context menu

- src/main.cpp
- src/ui/MainWindow.cpp
- src/ui/MainWindow.h
It doesn't seem worth translating and simplifying this error; it should
generally only apply for technical users with their own Qt.
Related to #174.
> ui: Show an error and exit if the root QML fails to load.

- BUILDING.md
The qtdeclarative5-controls-plugin package looks to be Ubuntu-specific,
and even as of Ubuntu 14.10, it uses the new qml-module-qtquick form.
Fixes #173 and #174
> doc: Update build dependency packages for Debian

- src/protocol/AuthHiddenServiceChannel.cpp
~~Increases the limit on our local key to match validation for partner's key in an incoming connection~~
Sets the limit for both directions to 150 bytes to allow slightly unusual but still valid keys
Fixes #186
> Allow public keys up to 150 bytes (DER)

- src/utils/SecureRNG.cpp
- src/utils/SecureRNG.h
Fixes #164, and one of the suggestions from #89.
> Fix SecureRNG return value and make RNG errors fatal

- src/ui/qml/MessageDelegate.qml
This needs a private API of QtQuickControls; I can't find a way to do it
with public API. The alternative is to move the menu instance outside of
MessageDelegate, and have a single instance of it always created for the
view.
> Fix leak of MessageDelegate context menu objects

- src/ui/qml/ChatPage.qml
This limit is applied by the protocol, so it should be apparent in UI as
well.
Also fixes a QTextCursor warning after sending messages, caused by
setting the text property instead of using remove().
> Limit chat message length in UI

- src/ui/qml/ChatMessageArea.qml
- src/ui/qml/MessageDelegate.qml
ScrollView is extremely buggy, and seems to regress in every Qt release.
It has a lot of trouble keeping the view scrolled to the bottom, and
with moving at a predictable rate in response to wheel events.
Writing a simple visual scrollbar and wheel handling manually makes for
a much better experience, even if we lose some platform-native scrollbar
behaviors.
---
This could use more testing on Qt <5.4, and on Windows or older Linux systems. It fixes a few Qt 5.5 regressions (#233).
> Use custom scrolling instead of ScrollView

- contrib/usr.bin.ricochet-apparmor
Add "owner @{HOME}/.gtkrc-2.0 r," to apparmor profile, giving Ricochet access to GTK theme information.
> Allow access to gtkrc-2.0

- src/ui/qml/main.qml
When contact request comes main.qml creates dialog without setting
parent window. It allow to open more contact requests dialogs even
if other dialogs are opened (including AddContactDialog).
I use KDE 4.14.2 and it works for me.
> Resolve problem #74

- BUILDING.md
Appears Qt's certificates have changes and qt-project.org no longer works over TLS.  It's possible https://www.qt.io/download-open-source/ is preferable.
> Certificats change

- src/core/ContactUser.cpp
- src/core/ContactUser.h
- src/core/ConversationModel.cpp
- src/core/IncomingRequestManager.cpp
- src/core/IncomingRequestManager.h
- src/core/OutgoingContactRequest.cpp
- src/core/OutgoingContactRequest.h
- src/core/UserIdentity.cpp
- src/core/UserIdentity.h
- src/protocol/Connection.cpp
- src/protocol/Connection.h
- src/protocol/OutboundConnector.cpp
- src/protocol/OutboundConnector.h
This makes the ownership of a Connection more clear, and removes a
lot of sketchy use of deleteLater to try to ensure connections are
always cleaned up at the right times.
> Use QSharedPointer for Connection ownership

- src/protocol/ContactRequestChannel.cpp
- src/ui/MainWindow.cpp
- src/ui/qml/Bubble.qml
- src/ui/qml/ChatPage.qml
- src/ui/qml/ContactIDField.qml
- src/ui/qml/ContactList.qml
- src/ui/qml/ContactListDelegate.qml
- src/ui/qml/ContactPreferences.qml
- src/ui/qml/ContactRequestFields.qml
- src/ui/qml/MessageDelegate.qml
- src/ui/qml/MessageDialogWrapper.qml
- src/ui/qml/OpenBrowserDialog.qml
- src/ui/qml/TorBootstrapStatus.qml
- src/ui/qml/TorLogDisplay.qml
- src/ui/qml/TorPreferences.qml
- src/ui/qml/qml.qrc
- src/ui/qml/utils.js
> QML makes the questionable decision of parsing all Text items as
rich text if they appear to like HTML. This HTML parser is, fortunately,
nothing like a browser - it supports only simple visual formatting.
Still, in the worst case it can trigger network requests.
> We were being too lax with sanitizing variables before display, if they
weren't directly from an external source. In one case, this could lead
to deanonymization if a user reviews and accepts a contact request
with a nickname containing an <img> tag.
These commits harden against this problem in three ways: by blocking any possible network requests, ensuring nicknames are sanitized every time they're displayed, and by blocking a few more characters in incoming contact requests.
Nicknames in Ricochet are always set by the local …
> Sanitize nicknames more carefully

- src/tor/TorSocket.cpp
On recent builds, Ricochet was failing to reconnect to contacts after a first failed attempt, because the connection to the SOCKS proxy was stuck in a failed state. Fix this by closing the TorSocket after a failure, making Qt reset the internal SOCKS connection.
Fixes #295
> Clear internal socket state after failed connections

- src/tor/TorControl.cpp
- src/tor/TorControl.h
- src/tor/TorManager.cpp
- src/ui/qml/TorConfigurationPage.qml
- src/ui/qml/TorPreferences.qml
```
If the TOR_CONTROL_PORT environment variable is present, use that
external instance of Tor instead of launching a bundled one.
TOR_CONTROL_HOST and TOR_CONTROL_PASSWD are also available for the
control hostname and password respectively. These variables match
the names used by Tor Browser.
There is no need to configure the SOCKS address; Ricochet will discover
it automatically.
```
Also, avoid making destructive changes to a tor instance we didn't start, by tracking whether we've taken ownership or not.
> Allow configuring external Tor in the environment

- ricochet.pro
- src/core/ContactUser.cpp
- src/core/UserIdentity.cpp
- src/core/UserIdentity.h
- src/tor/AddOnionCommand.cpp
- src/tor/AddOnionCommand.h
- src/tor/HiddenService.cpp
- src/tor/HiddenService.h
- src/tor/TorControl.cpp
- src/tor/TorControl.h
- src/utils/CryptoKey.cpp
- src/utils/CryptoKey.h
- tests/tests.pro
- tests/tst_cryptokey/tst_cryptokey.cpp
- tests/tst_cryptokey/tst_cryptokey.pro
For Tor >= 0.2.7, start using the ADD_ONION control command instead of SETCONF to configure hidden services, and store the private keys in our configuration file instead of as separate files on the filesystem.
Older versions of Tor remain supported, and the behavior will not change. There is an edge case where a profile is created with a new version of Tor and later downgraded - this is not supported. Don't do that.
Existing profiles will copy their keys into the configuration and stop using the files on disk, but those files will not be removed yet to help avoid any risk of data loss. They will be removed later, likely when we enable profile encryption.
Fixes #227
> Use Tor's ADD_ONION command when available

- src/ui/LinkedText.cpp
When formatting links to be displayed in messages, using repeated calls
to QString::arg() will interpret '%0' and similar in the URL as a
placeholder, resulting in the link not being properly formatted.
Depending on the value, this can either result in a broken URL when
copied to the clipboard (#403), or the URL being displayed with a label
of just '%2' (#372).
This cannot be used to mislabel links, and there is no printf-style
format vulnerability with QString::arg. There is no security impact.
> Fix parsing of links containing escape sequences

- src/ui/qml/NetworkSetupWizard.qml
These window animations seem to break a lot of platforms, and generally
just look bad on everything except OS X. We're better off without them.
Fixes #417
> Don't animate window resizes in network setup

- BUILDING.md
Add caveat to get around openssl includes having been removed in El
Capitan.
Add some step by step instructions including explicitly using qt5 qmake
since brew qt5 is keg only due to potential qt4/5 conflicts.
> add some osx caveats to BUILDING doc

- src/main.cpp
- src/utils/CryptoKey.cpp
OpenSSL 1.1 introduces some API changes (https://wiki.openssl.org/index.php/1.1_API_Changes) which affect building of Ricochet. This PR adds some extra code to enable compiling with both the old and the new API. *Please review carefully before merging!*
> add support for OpenSSL 1.1

- BUILDING.md
- README.md
Fixes misspelling of "withholding" in the README. 
Separately, should the sentence "It hasn't been audited or formally reviewed by anyone" be edited considering there was [an audit](https://ricochet.im/files/ricochet-ncc-audit-2016-01.pdf) released earlier this year? 
PS. Keep up the good work!
> fixes bad links and a misspelling

- src/main.cpp
See #367
Seems like there is a silent fallback to the default renderer if 'softwarecontext' isn't available. I'm getting good results with this renderer on our platforms with 5.6.2.
> Use the QtQuick 2D renderer by default

- ricochet.pro
For Linux, we need to include the ibus and compose input plugins for
some input methods to work (e.g. dead keys). See issue #60.
Also, we don't need playlists, mediaservice, imageformats, or printing.
Remove those plugins from static builds. Unfortunately, this doesn't
remove them from deployment with windeployqt or macdeployqt.
> Deploy linux input plugins and remove unneeded plugins

- src/ui/qml/TorConfigurationPage.qml
ReachableAddresses has been around for a very long time, and FirewallPorts has been deprecated almost as long. Behavior makes more sense when just using ReachableAddresses. See #482.
> Use Tor's ReachableAddresses option instead of FirewallPorts

- src/core/ConversationModel.cpp
- src/core/ConversationModel.h
From issue #345:
@s-rah 
>Ricochet will store messages at any rate until ultimately running out of memory. Locally on my small system I can get up to ~1M messages before ricochet consistently crashes.
This patch prunes old messages in the chat window to a hardcoded limit.
> Limit conversation history to 1000 entries (#345)

- .travis.yml
Based off of the rules @kolodziej wrote long ago in #261 (with my apologies for not working more on it then!), these seem to be working travis rules for a Linux and OSX build.
This currently does nothing other than test compilation. The trusty Qt version is very old (5.2), so QML likely won't be very functional. I couldn't find a usable PPA offering any reasonable Qt versions.
Still, seems kinda useful. This could be tied into Coverity later also.
> Add .travis-ci.yml

- src/core/ContactUser.cpp
Issue: ricochet-im/ricochet#278
There was a race condition between ContactUser::deleteContact() and ContactUser::requestRemoved().
Thanks to @pokulo @rburchell
> Fix crash in ContactUser::deleteContact()

- README.md
It has now been over a year since the NCC Group audit:
* https://motherboard.vice.com/en_us/article/ricochet-encrypted-messenger-tackles-metadata-problem-head-on
* https://ricochet.im/files/ricochet-ncc-audit-2016-01.pdf
> Don't say Ricochet hasn't been audited
